### ISSUE TITLE
Problem on Raspberry Pi 3B+

### ISSUE THREAD

**Issue by kazz2020** [WayzDev/Kage#8]
When i put npm run dev i have got this:
Version: webpack 4.31.0
  Time: 1092ms
  Built at: 05/10/2019 5:51:11 PM
    Asset      Size  Chunks  Chunk Names
  main.js  9.26 KiB    main  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./src/main/index.dev.js] 2.33 KiB {main} [not cacheable] [built] [failed] [1 error]
  [./src/main/index.js] 2.23 KiB {main} [not cacheable] [built] [failed] [1 error]
  
  ERROR in ./src/main/index.dev.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (/root/Kage/node_modules/babel-loader/lib/index.js:10:11)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at loadLoader (/root/Kage/node_modules/loader-runner/lib/loadLoader.js:18:17)
      at iteratePitchingLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
      at runLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
      at NormalModule.doBuild (/root/Kage/node_modules/webpack/lib/NormalModule.js:280:3)
      at NormalModule.build (/root/Kage/node_modules/webpack/lib/NormalModule.js:427:15)
      at Compilation.buildModule (/root/Kage/node_modules/webpack/lib/Compilation.js:635:10)
      at factory.create (/root/Kage/node_modules/webpack/lib/Compilation.js:884:14)
      at factory (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
      at hooks.afterResolve.callAsync (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
      at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/root/Kage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesWaterfallHook.lazyCompileHook (/root/Kage/node_modules/tapable/lib/Hook.js:154:20)
      at resolver (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
      at process.nextTick (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)
   @ multi ./src/main/index.dev.js ./src/main/index.js main[0]
  
  ERROR in ./src/main/index.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (/root/Kage/node_modules/babel-loader/lib/index.js:10:11)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at loadLoader (/root/Kage/node_modules/loader-runner/lib/loadLoader.js:18:17)
      at iteratePitchingLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
      at runLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
      at NormalModule.doBuild (/root/Kage/node_modules/webpack/lib/NormalModule.js:280:3)
      at NormalModule.build (/root/Kage/node_modules/webpack/lib/NormalModule.js:427:15)
      at Compilation.buildModule (/root/Kage/node_modules/webpack/lib/Compilation.js:635:10)
      at factory.create (/root/Kage/node_modules/webpack/lib/Compilation.js:884:14)
      at factory (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
      at hooks.afterResolve.callAsync (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
      at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/root/Kage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at resolver (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
      at process.nextTick (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)
   @ multi ./src/main/index.dev.js ./src/main/index.js main[1]

��� ----------------------------

��� Renderer Process -----------

  Hash: 52caa787c7eb279541a8
  Version: webpack 4.31.0
  Time: 4689ms
  Built at: 05/10/2019 5:51:15 PM
        Asset     Size    Chunks  Chunk Names
  renderer.js  733 KiB  renderer  renderer
  Entrypoint renderer = renderer.js
  [1] multi (webpack)-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 2.23 KiB {renderer} [not cacheable] [built] [failed] [1 error]
  [./node_modules/ansi-html/index.js] 4.16 KiB {renderer} [built]
  [./node_modules/ansi-regex/index.js] 135 bytes {renderer} [built]
  [./node_modules/html-entities/index.js] 231 bytes {renderer} [built]
  [./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {renderer} [built]
  [./node_modules/strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 8.26 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {renderer} [built]
  [./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {renderer} [built]
  [./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {renderer} [built]
  [./src/renderer/main.js] 2.23 KiB {renderer} [not cacheable] [built] [failed] [1 error]
  [querystring] external "querystring" 42 bytes {renderer} [built]
  [url] external "url" 42 bytes {renderer} [built]
      + 7 hidden modules
  
  ERROR in ./src/renderer/main.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (/root/Kage/node_modules/babel-loader/lib/index.js:10:11)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at loadLoader (/root/Kage/node_modules/loader-runner/lib/loadLoader.js:18:17)
      at iteratePitchingLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
      at runLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
      at NormalModule.doBuild (/root/Kage/node_modules/webpack/lib/NormalModule.js:280:3)
      at NormalModule.build (/root/Kage/node_modules/webpack/lib/NormalModule.js:427:15)
      at Compilation.buildModule (/root/Kage/node_modules/webpack/lib/Compilation.js:635:10)
      at factory.create (/root/Kage/node_modules/webpack/lib/Compilation.js:884:14)
      at factory (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
      at hooks.afterResolve.callAsync (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
      at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/root/Kage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at resolver (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
      at process.nextTick (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js renderer[1]
  
  ERROR in ./.electron-vue/dev-client.js
  Module build failed (from ./node_modules/babel-loader/lib/index.js):
  Error: Cannot find module '@babel/core'
   babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
      at Function.Module._load (internal/modules/cjs/loader.js:507:25)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at Object.<anonymous> (/root/Kage/node_modules/babel-loader/lib/index.js:10:11)
      at Module._compile (internal/modules/cjs/loader.js:689:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
      at Module.load (internal/modules/cjs/loader.js:599:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
      at Function.Module._load (internal/modules/cjs/loader.js:530:3)
      at Module.require (internal/modules/cjs/loader.js:637:17)
      at require (internal/modules/cjs/helpers.js:22:18)
      at loadLoader (/root/Kage/node_modules/loader-runner/lib/loadLoader.js:18:17)
      at iteratePitchingLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
      at runLoaders (/root/Kage/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
      at NormalModule.doBuild (/root/Kage/node_modules/webpack/lib/NormalModule.js:280:3)
      at NormalModule.build (/root/Kage/node_modules/webpack/lib/NormalModule.js:427:15)
      at Compilation.buildModule (/root/Kage/node_modules/webpack/lib/Compilation.js:635:10)
      at factory.create (/root/Kage/node_modules/webpack/lib/Compilation.js:884:14)
      at factory (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:405:6)
      at hooks.afterResolve.callAsync (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
      at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/root/Kage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at resolver (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
      at process.nextTick (/root/Kage/node_modules/webpack/lib/NormalModuleFactory.js:342:9)
      at process._tickCallback (internal/process/next_tick.js:61:11)
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js renderer[0]
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.22 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

��� ----------------------------

��� Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/d3b06545-e1d3-4223-b6f7-5928e0ece0cd
  For help see https://nodejs.org/en/docs/inspector
  
��� ----------------------------

��� Electron -------------------

  Error launching app
  Unable to find Electron app at /root/Kage/dist/electron/main.js
  
  Cannot find module '/root/Kage/dist/electron/main.js'
  
��� ----------------------------

root@kali:~/Kage#

**Comment by Zerx0r** [comment]
Hmm not sure what is going on, have you updated Kage dependencies? or modified the package.json?

**Comment by kazz2020** [comment]
I have manage to install yarn. I think all dependencies install well but when i run yarn run dev after few moments i have big white rectangle and nothing happens . I cant do anything with my pi. I cant iven do  screenshot to show how it looks like. Does someone run successfully Kage on Raspberry Pi 3B+ on kali ?

**Comment by Zerx0r** [comment]
When you run `yarn run dev`, is the console print any errors there in the white screen (chromium dev console ), if there is any please share it here

**Comment by kazz2020** [comment]
root@kali:~/Kage# yarn
yarn install v1.16.0
[1/4] Resolving packages...
success Already up-to-date.
$ npm run lint:fix
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1558119342912-0.6087195339138336/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kage@0.1.1-beta lint:fix /root/Kage
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src

Done in 27.25s.


 compiling...

��� ----------------------------

��� Main Process ---------------

  Hash: 913586cd98ea5813563d
  Version: webpack 4.31.0
  Time: 46543ms
  Built at: 05/17/2019 6:57:43 PM
    Asset     Size  Chunks             Chunk Names
  main.js  217 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {main} [built]
  [./node_modules/electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/downloadChromeExtension.js] 2.26 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]
  [./node_modules/electron-devtools-installer/dist/utils.js] 1.88 KiB {main} [built]
  [./node_modules/electron-is-dev/index.js] 256 bytes {main} [built]
  [./node_modules/electron-localshortcut/index.js] 8.16 KiB {main} [built]
  [./node_modules/semver/semver.js] 37.9 KiB {main} [built]
  [./src/main/index.dev.js] 364 bytes {main} [built]
  [./src/main/index.js] 1.34 KiB {main} [built]
  [./src/renderer/store/index.js] 294 bytes {main} [built]
  [./src/renderer/store/modules/index.js] 238 bytes {main} [built]
  [electron] external "electron" 42 bytes {main} [built]
  [fs] external "fs" 42 bytes {main} [built]
      + 40 hidden modules
  
  WARNING in ./node_modules/electron-debug/index.js 81:45-58
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js
  
  WARNING in ./node_modules/electron-debug/index.js 84:85-106
  Critical dependency: the request of a dependency is an expression
   @ ./src/main/index.dev.js
   @ multi ./src/main/index.dev.js ./src/main/index.js

��� ----------------------------

��� Renderer Process -----------

  Hash: 47eec0a02db2c1078139
  Version: webpack 4.31.0
  Time: 52445ms
  Built at: 05/17/2019 6:57:49 PM
                            Asset       Size    Chunks             Chunk Names
   fonts/element-icons--fonts.ttf   54.6 KiB            [emitted]  
  fonts/element-icons--fonts.woff   27.5 KiB            [emitted]  
                       index.html  447 bytes            [emitted]  
                      renderer.js   6.63 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [0] multi ./.electron-vue/dev-client ./src/renderer/main.js 40 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
  [./node_modules/element-ui/lib/element-ui.common.js] 1020 KiB {renderer} [built]
  [./node_modules/element-ui/lib/locale/lang/en.js] 2.49 KiB {renderer} [built]
  [./node_modules/element-ui/lib/theme-chalk/index.css] 934 bytes {renderer} [built]
  [./node_modules/vue/dist/vue.esm.js] 318 KiB {renderer} [built]
  [./node_modules/webpack-hot-middleware/client.js?noInfo=true&reload=true] (webpack)-hot-middleware/client.js?noInfo=true&reload=true 7.68 KiB {renderer} [built]
  [./src/renderer/App.vue] 1.08 KiB {renderer} [built]
  [./src/renderer/main.js] 1.12 KiB {renderer} [built]
  [./src/renderer/router/index.js] 680 bytes {renderer} [built]
  [./src/renderer/store/index.js] 294 bytes {renderer} [built]
  [@fortawesome/fontawesome-svg-core] external "@fortawesome/fontawesome-svg-core" 42 bytes {renderer} [built]
  [@fortawesome/free-solid-svg-icons] external "@fortawesome/free-solid-svg-icons" 42 bytes {renderer} [built]
  [@fortawesome/vue-fontawesome] external "@fortawesome/vue-fontawesome" 42 bytes {renderer} [built]
  [axios] external "axios" 42 bytes {renderer} [built]
      + 269 hidden modules
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.38 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.22 KiB {0} [built]
      [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
      [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

��� ----------------------------

��� Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/d11330c3-ba94-491f-b74a-54ac1b4f1b6b
  For help see https://nodejs.org/en/docs/inspector
  
��� ----------------------------


Now the situation is:
When i power on Raspberry Pi and run yarn run dev the Kage start i can see logo and after long time i can see program window but its so slow and laggy ...i cant even copy and paste console normal because its not normal behavior ...in this situation using is impossible....

**Comment by kazz2020** [comment]
s

**Comment by Zerx0r** [comment]
How many ram do you in your Raspberry Pi. The lag might be because of ram.

**Comment by kazz2020** [comment]
This version has 1GB ram

**Comment by necrose99** [comment]
RPI4 4 gigs of RAM , **OUT OF STOCK ? (Most places still) but newer 8GIGS** of ram.  
[Digikey might have. ](https://www.digikey.com/product-detail/en/raspberry-pi/RASPBERRY%2520PI%25204%2520MODEL%2520B%25208G/1690-RASPBERRYPI4MODELB8G-ND/12159401)
and 64bit os Like[ Gentoo](https://github.com/sakaki-/gentoo-on-rpi-64bit) for the @Pentoo

**Comment by necrose99** [comment]
electron-builder -mwl   https://www.electron.build/multi-platform-build

kage-0.1.1-beta-armv7l.tar.gz  kage-0.1.1-beta-arm64.tar.gz  and or app images , with a bit of fiddling , yarn build will take the electron build values and do them. 

--arm64 --armv7l will do for arm64/arm32.... 

Ironically the Mac flag did build a x64 macos package on rpi4 , however kinda pointless.  since no mac.
